function readinfo = trials_readvalidtrials(workbookFile, sheetName, dataLines)
%IMPORTFILE Import data from a spreadsheet
%  VALIDTRIALSBRAD = IMPORTFILE(FILE) reads data from the first
%  worksheet in the Microsoft Excel spreadsheet file named FILE.
%  Returns the data as a string array.
%
%  VALIDTRIALSBRAD = IMPORTFILE(FILE, SHEET) reads from the specified
%  worksheet.
%
%  VALIDTRIALSBRAD = IMPORTFILE(FILE, SHEET, DATALINES) reads from the
%  specified worksheet for the specified row interval(s). Specify
%  DATALINES as a positive scalar integer or a N-by-2 array of positive
%  scalar integers for dis-contiguous row intervals.
%
%  Example:
%  validtrialsbrad = importfile("F:\Andrew\Documents\MATLAB\Thesis\validtrials_brad.xlsx", "Sheet1", [2, 29]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 25-Aug-2020 12:14:10

%% Input handling

% If no sheet is specified, read first sheet
if nargin == 1 || isempty(sheetName)
    sheetName = 1;
end

% If row start and end points are not specified, define defaults
if nargin <= 2
    dataLines = [2, 29];
end

%% Setup the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 3);

% Specify sheet and range
opts.Sheet = sheetName;
opts.DataRange = "A" + dataLines(1, 1) + ":C" + dataLines(1, 2);

% Specify column names and types
opts.VariableNames = ["FileName", "Foot", "ForcePlates"];
opts.VariableTypes = ["string", "string", "string"];

% Specify variable properties
opts = setvaropts(opts, ["FileName", "Foot", "ForcePlates"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["FileName", "Foot", "ForcePlates"], "EmptyFieldRule", "auto");

% Import the data
readinfo = readmatrix(workbookFile, opts, "UseExcel", false);

for idx = 2:size(dataLines, 1)
    opts.DataRange = "A" + dataLines(idx, 1) + ":C" + dataLines(idx, 2);
    tb = readmatrix(workbookFile, opts, "UseExcel", false);
    readinfo = [readinfo; tb]; %#ok<AGROW>
end

end